const mockFollowers = [
  {
    login: "esin",
    id: 69767,
    node_id: "MDQ6VXNlcjY5NzY3",
    avatar_url: "https://avatars.githubusercontent.com/u/69767?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/esin",
    html_url: "https://github.com/esin",
    followers_url: "https://api.github.com/users/esin/followers",
    following_url: "https://api.github.com/users/esin/following{/other_user}",
    gists_url: "https://api.github.com/users/esin/gists{/gist_id}",
    starred_url: "https://api.github.com/users/esin/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/esin/subscriptions",
    organizations_url: "https://api.github.com/users/esin/orgs",
    repos_url: "https://api.github.com/users/esin/repos",
    events_url: "https://api.github.com/users/esin/events{/privacy}",
    received_events_url: "https://api.github.com/users/esin/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "PFacklam",
    id: 956673,
    node_id: "MDQ6VXNlcjk1NjY3Mw==",
    avatar_url: "https://avatars.githubusercontent.com/u/956673?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/PFacklam",
    html_url: "https://github.com/PFacklam",
    followers_url: "https://api.github.com/users/PFacklam/followers",
    following_url:
      "https://api.github.com/users/PFacklam/following{/other_user}",
    gists_url: "https://api.github.com/users/PFacklam/gists{/gist_id}",
    starred_url: "https://api.github.com/users/PFacklam/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/PFacklam/subscriptions",
    organizations_url: "https://api.github.com/users/PFacklam/orgs",
    repos_url: "https://api.github.com/users/PFacklam/repos",
    events_url: "https://api.github.com/users/PFacklam/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/PFacklam/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Mahmoud-Italy",
    id: 17962343,
    node_id: "MDQ6VXNlcjE3OTYyMzQz",
    avatar_url: "https://avatars.githubusercontent.com/u/17962343?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Mahmoud-Italy",
    html_url: "https://github.com/Mahmoud-Italy",
    followers_url: "https://api.github.com/users/Mahmoud-Italy/followers",
    following_url:
      "https://api.github.com/users/Mahmoud-Italy/following{/other_user}",
    gists_url: "https://api.github.com/users/Mahmoud-Italy/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Mahmoud-Italy/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Mahmoud-Italy/subscriptions",
    organizations_url: "https://api.github.com/users/Mahmoud-Italy/orgs",
    repos_url: "https://api.github.com/users/Mahmoud-Italy/repos",
    events_url: "https://api.github.com/users/Mahmoud-Italy/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Mahmoud-Italy/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "AYIDouble",
    id: 18186995,
    node_id: "MDQ6VXNlcjE4MTg2OTk1",
    avatar_url: "https://avatars.githubusercontent.com/u/18186995?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/AYIDouble",
    html_url: "https://github.com/AYIDouble",
    followers_url: "https://api.github.com/users/AYIDouble/followers",
    following_url:
      "https://api.github.com/users/AYIDouble/following{/other_user}",
    gists_url: "https://api.github.com/users/AYIDouble/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/AYIDouble/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/AYIDouble/subscriptions",
    organizations_url: "https://api.github.com/users/AYIDouble/orgs",
    repos_url: "https://api.github.com/users/AYIDouble/repos",
    events_url: "https://api.github.com/users/AYIDouble/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/AYIDouble/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "PranamBhat",
    id: 32120033,
    node_id: "MDQ6VXNlcjMyMTIwMDMz",
    avatar_url: "https://avatars.githubusercontent.com/u/32120033?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/PranamBhat",
    html_url: "https://github.com/PranamBhat",
    followers_url: "https://api.github.com/users/PranamBhat/followers",
    following_url:
      "https://api.github.com/users/PranamBhat/following{/other_user}",
    gists_url: "https://api.github.com/users/PranamBhat/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/PranamBhat/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/PranamBhat/subscriptions",
    organizations_url: "https://api.github.com/users/PranamBhat/orgs",
    repos_url: "https://api.github.com/users/PranamBhat/repos",
    events_url: "https://api.github.com/users/PranamBhat/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/PranamBhat/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "liling0509",
    id: 35401210,
    node_id: "MDQ6VXNlcjM1NDAxMjEw",
    avatar_url: "https://avatars.githubusercontent.com/u/35401210?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/liling0509",
    html_url: "https://github.com/liling0509",
    followers_url: "https://api.github.com/users/liling0509/followers",
    following_url:
      "https://api.github.com/users/liling0509/following{/other_user}",
    gists_url: "https://api.github.com/users/liling0509/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/liling0509/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/liling0509/subscriptions",
    organizations_url: "https://api.github.com/users/liling0509/orgs",
    repos_url: "https://api.github.com/users/liling0509/repos",
    events_url: "https://api.github.com/users/liling0509/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/liling0509/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "sinha-kush",
    id: 44023793,
    node_id: "MDQ6VXNlcjQ0MDIzNzkz",
    avatar_url: "https://avatars.githubusercontent.com/u/44023793?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/sinha-kush",
    html_url: "https://github.com/sinha-kush",
    followers_url: "https://api.github.com/users/sinha-kush/followers",
    following_url:
      "https://api.github.com/users/sinha-kush/following{/other_user}",
    gists_url: "https://api.github.com/users/sinha-kush/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/sinha-kush/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/sinha-kush/subscriptions",
    organizations_url: "https://api.github.com/users/sinha-kush/orgs",
    repos_url: "https://api.github.com/users/sinha-kush/repos",
    events_url: "https://api.github.com/users/sinha-kush/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/sinha-kush/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "AakashTudu",
    id: 44318049,
    node_id: "MDQ6VXNlcjQ0MzE4MDQ5",
    avatar_url: "https://avatars.githubusercontent.com/u/44318049?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/AakashTudu",
    html_url: "https://github.com/AakashTudu",
    followers_url: "https://api.github.com/users/AakashTudu/followers",
    following_url:
      "https://api.github.com/users/AakashTudu/following{/other_user}",
    gists_url: "https://api.github.com/users/AakashTudu/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/AakashTudu/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/AakashTudu/subscriptions",
    organizations_url: "https://api.github.com/users/AakashTudu/orgs",
    repos_url: "https://api.github.com/users/AakashTudu/repos",
    events_url: "https://api.github.com/users/AakashTudu/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/AakashTudu/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "vitasha10",
    id: 45239133,
    node_id: "MDQ6VXNlcjQ1MjM5MTMz",
    avatar_url: "https://avatars.githubusercontent.com/u/45239133?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/vitasha10",
    html_url: "https://github.com/vitasha10",
    followers_url: "https://api.github.com/users/vitasha10/followers",
    following_url:
      "https://api.github.com/users/vitasha10/following{/other_user}",
    gists_url: "https://api.github.com/users/vitasha10/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/vitasha10/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/vitasha10/subscriptions",
    organizations_url: "https://api.github.com/users/vitasha10/orgs",
    repos_url: "https://api.github.com/users/vitasha10/repos",
    events_url: "https://api.github.com/users/vitasha10/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/vitasha10/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ijagjeet",
    id: 46004289,
    node_id: "MDQ6VXNlcjQ2MDA0Mjg5",
    avatar_url: "https://avatars.githubusercontent.com/u/46004289?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ijagjeet",
    html_url: "https://github.com/ijagjeet",
    followers_url: "https://api.github.com/users/ijagjeet/followers",
    following_url:
      "https://api.github.com/users/ijagjeet/following{/other_user}",
    gists_url: "https://api.github.com/users/ijagjeet/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ijagjeet/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ijagjeet/subscriptions",
    organizations_url: "https://api.github.com/users/ijagjeet/orgs",
    repos_url: "https://api.github.com/users/ijagjeet/repos",
    events_url: "https://api.github.com/users/ijagjeet/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ijagjeet/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jdevstatic",
    id: 47092464,
    node_id: "MDQ6VXNlcjQ3MDkyNDY0",
    avatar_url: "https://avatars.githubusercontent.com/u/47092464?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jdevstatic",
    html_url: "https://github.com/jdevstatic",
    followers_url: "https://api.github.com/users/jdevstatic/followers",
    following_url:
      "https://api.github.com/users/jdevstatic/following{/other_user}",
    gists_url: "https://api.github.com/users/jdevstatic/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/jdevstatic/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jdevstatic/subscriptions",
    organizations_url: "https://api.github.com/users/jdevstatic/orgs",
    repos_url: "https://api.github.com/users/jdevstatic/repos",
    events_url: "https://api.github.com/users/jdevstatic/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/jdevstatic/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "PremChapagain",
    id: 47587012,
    node_id: "MDQ6VXNlcjQ3NTg3MDEy",
    avatar_url: "https://avatars.githubusercontent.com/u/47587012?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/PremChapagain",
    html_url: "https://github.com/PremChapagain",
    followers_url: "https://api.github.com/users/PremChapagain/followers",
    following_url:
      "https://api.github.com/users/PremChapagain/following{/other_user}",
    gists_url: "https://api.github.com/users/PremChapagain/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/PremChapagain/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/PremChapagain/subscriptions",
    organizations_url: "https://api.github.com/users/PremChapagain/orgs",
    repos_url: "https://api.github.com/users/PremChapagain/repos",
    events_url: "https://api.github.com/users/PremChapagain/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/PremChapagain/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "albertmoons",
    id: 48081756,
    node_id: "MDQ6VXNlcjQ4MDgxNzU2",
    avatar_url: "https://avatars.githubusercontent.com/u/48081756?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/albertmoons",
    html_url: "https://github.com/albertmoons",
    followers_url: "https://api.github.com/users/albertmoons/followers",
    following_url:
      "https://api.github.com/users/albertmoons/following{/other_user}",
    gists_url: "https://api.github.com/users/albertmoons/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/albertmoons/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/albertmoons/subscriptions",
    organizations_url: "https://api.github.com/users/albertmoons/orgs",
    repos_url: "https://api.github.com/users/albertmoons/repos",
    events_url: "https://api.github.com/users/albertmoons/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/albertmoons/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Manikanta05",
    id: 50227418,
    node_id: "MDQ6VXNlcjUwMjI3NDE4",
    avatar_url: "https://avatars.githubusercontent.com/u/50227418?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Manikanta05",
    html_url: "https://github.com/Manikanta05",
    followers_url: "https://api.github.com/users/Manikanta05/followers",
    following_url:
      "https://api.github.com/users/Manikanta05/following{/other_user}",
    gists_url: "https://api.github.com/users/Manikanta05/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Manikanta05/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Manikanta05/subscriptions",
    organizations_url: "https://api.github.com/users/Manikanta05/orgs",
    repos_url: "https://api.github.com/users/Manikanta05/repos",
    events_url: "https://api.github.com/users/Manikanta05/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Manikanta05/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Shashank2k19",
    id: 53328541,
    node_id: "MDQ6VXNlcjUzMzI4NTQx",
    avatar_url: "https://avatars.githubusercontent.com/u/53328541?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Shashank2k19",
    html_url: "https://github.com/Shashank2k19",
    followers_url: "https://api.github.com/users/Shashank2k19/followers",
    following_url:
      "https://api.github.com/users/Shashank2k19/following{/other_user}",
    gists_url: "https://api.github.com/users/Shashank2k19/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Shashank2k19/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Shashank2k19/subscriptions",
    organizations_url: "https://api.github.com/users/Shashank2k19/orgs",
    repos_url: "https://api.github.com/users/Shashank2k19/repos",
    events_url: "https://api.github.com/users/Shashank2k19/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Shashank2k19/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "I-Atlas",
    id: 54947380,
    node_id: "MDQ6VXNlcjU0OTQ3Mzgw",
    avatar_url: "https://avatars.githubusercontent.com/u/54947380?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/I-Atlas",
    html_url: "https://github.com/I-Atlas",
    followers_url: "https://api.github.com/users/I-Atlas/followers",
    following_url:
      "https://api.github.com/users/I-Atlas/following{/other_user}",
    gists_url: "https://api.github.com/users/I-Atlas/gists{/gist_id}",
    starred_url: "https://api.github.com/users/I-Atlas/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/I-Atlas/subscriptions",
    organizations_url: "https://api.github.com/users/I-Atlas/orgs",
    repos_url: "https://api.github.com/users/I-Atlas/repos",
    events_url: "https://api.github.com/users/I-Atlas/events{/privacy}",
    received_events_url: "https://api.github.com/users/I-Atlas/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "MdRashid62",
    id: 55427374,
    node_id: "MDQ6VXNlcjU1NDI3Mzc0",
    avatar_url: "https://avatars.githubusercontent.com/u/55427374?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/MdRashid62",
    html_url: "https://github.com/MdRashid62",
    followers_url: "https://api.github.com/users/MdRashid62/followers",
    following_url:
      "https://api.github.com/users/MdRashid62/following{/other_user}",
    gists_url: "https://api.github.com/users/MdRashid62/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/MdRashid62/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/MdRashid62/subscriptions",
    organizations_url: "https://api.github.com/users/MdRashid62/orgs",
    repos_url: "https://api.github.com/users/MdRashid62/repos",
    events_url: "https://api.github.com/users/MdRashid62/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/MdRashid62/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ShaliniGupta06",
    id: 56738634,
    node_id: "MDQ6VXNlcjU2NzM4NjM0",
    avatar_url: "https://avatars.githubusercontent.com/u/56738634?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ShaliniGupta06",
    html_url: "https://github.com/ShaliniGupta06",
    followers_url: "https://api.github.com/users/ShaliniGupta06/followers",
    following_url:
      "https://api.github.com/users/ShaliniGupta06/following{/other_user}",
    gists_url: "https://api.github.com/users/ShaliniGupta06/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ShaliniGupta06/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/ShaliniGupta06/subscriptions",
    organizations_url: "https://api.github.com/users/ShaliniGupta06/orgs",
    repos_url: "https://api.github.com/users/ShaliniGupta06/repos",
    events_url: "https://api.github.com/users/ShaliniGupta06/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ShaliniGupta06/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Rounik10",
    id: 56750020,
    node_id: "MDQ6VXNlcjU2NzUwMDIw",
    avatar_url: "https://avatars.githubusercontent.com/u/56750020?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Rounik10",
    html_url: "https://github.com/Rounik10",
    followers_url: "https://api.github.com/users/Rounik10/followers",
    following_url:
      "https://api.github.com/users/Rounik10/following{/other_user}",
    gists_url: "https://api.github.com/users/Rounik10/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Rounik10/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Rounik10/subscriptions",
    organizations_url: "https://api.github.com/users/Rounik10/orgs",
    repos_url: "https://api.github.com/users/Rounik10/repos",
    events_url: "https://api.github.com/users/Rounik10/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Rounik10/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Akshat0410",
    id: 56750869,
    node_id: "MDQ6VXNlcjU2NzUwODY5",
    avatar_url: "https://avatars.githubusercontent.com/u/56750869?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Akshat0410",
    html_url: "https://github.com/Akshat0410",
    followers_url: "https://api.github.com/users/Akshat0410/followers",
    following_url:
      "https://api.github.com/users/Akshat0410/following{/other_user}",
    gists_url: "https://api.github.com/users/Akshat0410/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Akshat0410/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Akshat0410/subscriptions",
    organizations_url: "https://api.github.com/users/Akshat0410/orgs",
    repos_url: "https://api.github.com/users/Akshat0410/repos",
    events_url: "https://api.github.com/users/Akshat0410/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Akshat0410/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Shivam7756",
    id: 56798691,
    node_id: "MDQ6VXNlcjU2Nzk4Njkx",
    avatar_url: "https://avatars.githubusercontent.com/u/56798691?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Shivam7756",
    html_url: "https://github.com/Shivam7756",
    followers_url: "https://api.github.com/users/Shivam7756/followers",
    following_url:
      "https://api.github.com/users/Shivam7756/following{/other_user}",
    gists_url: "https://api.github.com/users/Shivam7756/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Shivam7756/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Shivam7756/subscriptions",
    organizations_url: "https://api.github.com/users/Shivam7756/orgs",
    repos_url: "https://api.github.com/users/Shivam7756/repos",
    events_url: "https://api.github.com/users/Shivam7756/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Shivam7756/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Mayankjha997",
    id: 57581165,
    node_id: "MDQ6VXNlcjU3NTgxMTY1",
    avatar_url: "https://avatars.githubusercontent.com/u/57581165?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Mayankjha997",
    html_url: "https://github.com/Mayankjha997",
    followers_url: "https://api.github.com/users/Mayankjha997/followers",
    following_url:
      "https://api.github.com/users/Mayankjha997/following{/other_user}",
    gists_url: "https://api.github.com/users/Mayankjha997/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Mayankjha997/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Mayankjha997/subscriptions",
    organizations_url: "https://api.github.com/users/Mayankjha997/orgs",
    repos_url: "https://api.github.com/users/Mayankjha997/repos",
    events_url: "https://api.github.com/users/Mayankjha997/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Mayankjha997/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "alokkumar0723",
    id: 58732414,
    node_id: "MDQ6VXNlcjU4NzMyNDE0",
    avatar_url: "https://avatars.githubusercontent.com/u/58732414?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/alokkumar0723",
    html_url: "https://github.com/alokkumar0723",
    followers_url: "https://api.github.com/users/alokkumar0723/followers",
    following_url:
      "https://api.github.com/users/alokkumar0723/following{/other_user}",
    gists_url: "https://api.github.com/users/alokkumar0723/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/alokkumar0723/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/alokkumar0723/subscriptions",
    organizations_url: "https://api.github.com/users/alokkumar0723/orgs",
    repos_url: "https://api.github.com/users/alokkumar0723/repos",
    events_url: "https://api.github.com/users/alokkumar0723/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/alokkumar0723/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "kamalharsh14",
    id: 60378766,
    node_id: "MDQ6VXNlcjYwMzc4NzY2",
    avatar_url: "https://avatars.githubusercontent.com/u/60378766?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/kamalharsh14",
    html_url: "https://github.com/kamalharsh14",
    followers_url: "https://api.github.com/users/kamalharsh14/followers",
    following_url:
      "https://api.github.com/users/kamalharsh14/following{/other_user}",
    gists_url: "https://api.github.com/users/kamalharsh14/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/kamalharsh14/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/kamalharsh14/subscriptions",
    organizations_url: "https://api.github.com/users/kamalharsh14/orgs",
    repos_url: "https://api.github.com/users/kamalharsh14/repos",
    events_url: "https://api.github.com/users/kamalharsh14/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/kamalharsh14/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Shreedhar-Kushwaha",
    id: 60578563,
    node_id: "MDQ6VXNlcjYwNTc4NTYz",
    avatar_url: "https://avatars.githubusercontent.com/u/60578563?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Shreedhar-Kushwaha",
    html_url: "https://github.com/Shreedhar-Kushwaha",
    followers_url: "https://api.github.com/users/Shreedhar-Kushwaha/followers",
    following_url:
      "https://api.github.com/users/Shreedhar-Kushwaha/following{/other_user}",
    gists_url:
      "https://api.github.com/users/Shreedhar-Kushwaha/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Shreedhar-Kushwaha/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Shreedhar-Kushwaha/subscriptions",
    organizations_url: "https://api.github.com/users/Shreedhar-Kushwaha/orgs",
    repos_url: "https://api.github.com/users/Shreedhar-Kushwaha/repos",
    events_url:
      "https://api.github.com/users/Shreedhar-Kushwaha/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Shreedhar-Kushwaha/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "monicahnyokabi",
    id: 61146082,
    node_id: "MDQ6VXNlcjYxMTQ2MDgy",
    avatar_url: "https://avatars.githubusercontent.com/u/61146082?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/monicahnyokabi",
    html_url: "https://github.com/monicahnyokabi",
    followers_url: "https://api.github.com/users/monicahnyokabi/followers",
    following_url:
      "https://api.github.com/users/monicahnyokabi/following{/other_user}",
    gists_url: "https://api.github.com/users/monicahnyokabi/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/monicahnyokabi/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/monicahnyokabi/subscriptions",
    organizations_url: "https://api.github.com/users/monicahnyokabi/orgs",
    repos_url: "https://api.github.com/users/monicahnyokabi/repos",
    events_url: "https://api.github.com/users/monicahnyokabi/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/monicahnyokabi/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "kpranshul",
    id: 63549261,
    node_id: "MDQ6VXNlcjYzNTQ5MjYx",
    avatar_url: "https://avatars.githubusercontent.com/u/63549261?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/kpranshul",
    html_url: "https://github.com/kpranshul",
    followers_url: "https://api.github.com/users/kpranshul/followers",
    following_url:
      "https://api.github.com/users/kpranshul/following{/other_user}",
    gists_url: "https://api.github.com/users/kpranshul/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/kpranshul/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/kpranshul/subscriptions",
    organizations_url: "https://api.github.com/users/kpranshul/orgs",
    repos_url: "https://api.github.com/users/kpranshul/repos",
    events_url: "https://api.github.com/users/kpranshul/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/kpranshul/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "itiremiroglu",
    id: 63678712,
    node_id: "MDQ6VXNlcjYzNjc4NzEy",
    avatar_url: "https://avatars.githubusercontent.com/u/63678712?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/itiremiroglu",
    html_url: "https://github.com/itiremiroglu",
    followers_url: "https://api.github.com/users/itiremiroglu/followers",
    following_url:
      "https://api.github.com/users/itiremiroglu/following{/other_user}",
    gists_url: "https://api.github.com/users/itiremiroglu/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/itiremiroglu/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/itiremiroglu/subscriptions",
    organizations_url: "https://api.github.com/users/itiremiroglu/orgs",
    repos_url: "https://api.github.com/users/itiremiroglu/repos",
    events_url: "https://api.github.com/users/itiremiroglu/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/itiremiroglu/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "RASHI2505",
    id: 64950686,
    node_id: "MDQ6VXNlcjY0OTUwNjg2",
    avatar_url: "https://avatars.githubusercontent.com/u/64950686?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/RASHI2505",
    html_url: "https://github.com/RASHI2505",
    followers_url: "https://api.github.com/users/RASHI2505/followers",
    following_url:
      "https://api.github.com/users/RASHI2505/following{/other_user}",
    gists_url: "https://api.github.com/users/RASHI2505/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/RASHI2505/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/RASHI2505/subscriptions",
    organizations_url: "https://api.github.com/users/RASHI2505/orgs",
    repos_url: "https://api.github.com/users/RASHI2505/repos",
    events_url: "https://api.github.com/users/RASHI2505/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/RASHI2505/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Kushal334",
    id: 66548225,
    node_id: "MDQ6VXNlcjY2NTQ4MjI1",
    avatar_url: "https://avatars.githubusercontent.com/u/66548225?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Kushal334",
    html_url: "https://github.com/Kushal334",
    followers_url: "https://api.github.com/users/Kushal334/followers",
    following_url:
      "https://api.github.com/users/Kushal334/following{/other_user}",
    gists_url: "https://api.github.com/users/Kushal334/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Kushal334/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Kushal334/subscriptions",
    organizations_url: "https://api.github.com/users/Kushal334/orgs",
    repos_url: "https://api.github.com/users/Kushal334/repos",
    events_url: "https://api.github.com/users/Kushal334/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Kushal334/received_events",
    type: "User",
    site_admin: false,
  },
];
export default mockFollowers;
